credentials:
  usernames:
    admin:
      email: admin@email.com
      name: Admin
      password: Password2025!  # This should be hashed in production

cookie:
  expiry_days: 5
  key: 123ba9fff6d784eaf29b6d4ea47cc65fd006201d6ef58a22  # Must be string
  name: survey_dashboard_cookie